{
 "title": "Cloud Computation DashBoard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"episode-micro-service.default.svc.cluster.local:8082\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_memory_used_bytes{instance=\"people-micro-service.default.svc.cluster.local:8081\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_memory_used_bytes{instance=\"principals-micro-service.default.svc.cluster.local:8083\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_memory_used_bytes{instance=\"title-micro-service.default.svc.cluster.local:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoint HTTP Calls Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{instance=\"episode-micro-service.default.svc.cluster.local:8082\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_server_requests_seconds_count{instance=\"people-micro-service.default.svc.cluster.local:8081\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_server_requests_seconds_count{instance=\"principals-micro-service.default.svc.cluster.local:8083\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_server_requests_seconds_count{instance=\"title-micro-service.default.svc.cluster.local:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process CPU Usage ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "process_cpu_usage{instance=\"episode-micro-service.default.svc.cluster.local:8082\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_cpu_usage{instance=\"people-micro-service.default.svc.cluster.local:8081\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_cpu_usage{instance=\"principals-micro-service.default.svc.cluster.local:8083\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_cpu_usage{instance=\"title-micro-service.default.svc.cluster.local:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{instance=\"episode-micro-service.default.svc.cluster.local:8082\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_server_requests_seconds_sum{instance=\"episode-micro-service.default.svc.cluster.local:8082\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_server_requests_seconds_sum{instance=\"people-micro-service.default.svc.cluster.local:8081\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_server_requests_seconds_sum{instance=\"principals-micro-service.default.svc.cluster.local:8083\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_server_requests_seconds_sum{instance=\"title-micro-service.default.svc.cluster.local:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}