version: "3.9"
services:
    title-micro-service:
        build:
            context: ./tittles-micro-service
            dockerfile: Dockerfile
        image:  title-micro-service:latest
        ports:
            - '8888:8080'
        depends_on: 
            - postgres_db
    episode-micro-service:
        build:
            context: ./episode-micro-service
            dockerfile: Dockerfile
        image:  episode-micro-service:latest
        ports:
            - '8889:8080'
        depends_on: 
            - postgres_db
    people-micro-service:
        build:
            context: ./people-micro-service
            dockerfile: Dockerfile
        image:  people-micro-service:latest
        ports:
            - '8890:8080'
        depends_on: 
            - postgres_db
    principals-micro-service:
        build:
            context: ./principals-micro-service
            dockerfile: Dockerfile
        image:  principals-micro-service:latest
        ports:
            - '8887:8080'
        depends_on: 
            - postgres_db
    postgres_db:
        image: postgres
        volumes:
          - ./db_data:/var/lib/postgresql/data
          - ./data.sql:/docker-entrypoint-initdb.d/1-schema.sql
          - ./dataset:/dataset/
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
        ports:
          - '5432:5432'
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
