server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres-db-lb:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    platform: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
    # ddl-auto: create-drop
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: 6IfdQJ0dWmk3HBdIQ1TtFcHjJD7hpikV
            client-secret: 8yhrXJGtfaJh59t93CKvfiGmAhXWVdNv9_kps4wNZtR9WFlpBpRSQbqf3JeozToe
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-aula3bjod6orbofw.us.auth0.com/

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
#https://feilerdev.wordpress.com/2017/12/05/installing-postgresql-on-windows-using-zip-archive-without-the-installer/
#https://www.enterprisedb.com/download-postgresql-binaries
#pg_ctl.exe start -D ../data