server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres_db:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    platform: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
    # ddl-auto: create-drop
    show-sql: false

app:
  urls:
    title-micro-service: "http://title-micro-service:8080"

#https://feilerdev.wordpress.com/2017/12/05/installing-postgresql-on-windows-using-zip-archive-without-the-installer/
#https://www.enterprisedb.com/download-postgresql-binaries
#pg_ctl.exe start -D ../data